# Generated by Django 6.1.1 on 2026-09-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('gen_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('gen_descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('lib_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lib_titulo', models.CharField(max_length=200)),
                ('lib_autor', models.CharField(max_length=200)),
                ('lib_anio', models.CharField(max_length=4)),
                ('lib_cantidad', models.IntegerField()),
                ('lib_gen', models.ForeignKey(db_column='lib_gen_id', on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='accounts.genero')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('pre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pre_fechaprest', models.DateField()),
                ('pre_fechasalida', models.DateField()),
                ('pre_lib', models.ForeignKey(db_column='pre_lib_id', on_delete=django.db.models.deletion.PROTECT, related_name='prestaciones', to='accounts.libro')),
            ],
            options={
                'db_table': 'Prestaciones',
            },
        ),
    ]
