# Generated by Django 6.1.1 on 2026-09-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='prestacion',
            options={'verbose_name': 'Prestación', 'verbose_name_plural': 'Prestaciones'},
        ),
        migrations.AlterField(
            model_name='genero',
            name='gen_descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='gen_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_anio',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_autor',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_cantidad',
            field=models.IntegerField(verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_gen',
            field=models.ForeignKey(db_column='lib_gen_id', on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='accounts.genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='pre_fechaprest',
            field=models.DateField(verbose_name='Fecha de préstamo'),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='pre_fechasalida',
            field=models.DateField(verbose_name='Fecha de salida'),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='pre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='pre_lib',
            field=models.ForeignKey(db_column='pre_lib_id', on_delete=django.db.models.deletion.PROTECT, related_name='prestaciones', to='accounts.libro', verbose_name='Libro'),
        ),
    ]
