# Generated by Django 6.1.1 on 2026-09-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_genero_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacion',
            name='pre_cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
