# Generated by Django 6.1.1 on 2026-09-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_prestacion_pre_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('dev_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_cantidad', models.PositiveIntegerField(verbose_name='Cantidad devuelta')),
                ('dev_fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de devolución')),
                ('dev_prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='accounts.prestacion', verbose_name='Prestación')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'Devoluciones',
            },
        ),
    ]
